# Generated by Django 2.2.24 on 2021-09-05 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Soru')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma tarihi')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='question_pictures')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='spaces.Spaces')),
                ('downvoters', models.ManyToManyField(blank=True, related_name='downvoterssq', to=settings.AUTH_USER_MODEL)),
                ('upvoters', models.ManyToManyField(blank=True, related_name='upvoterssq', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spacequestions', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceQuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='sqyorum')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100, verbose_name='user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spacecomments', to='ask.SpaceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120, verbose_name='Soru')),
                ('publishing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayınlanma tarihi')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='question_pictures', verbose_name='picture')),
                ('downvoters', models.ManyToManyField(blank=True, related_name='downvoters', to=settings.AUTH_USER_MODEL)),
                ('upvoters', models.ManyToManyField(blank=True, related_name='upvoters', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100, verbose_name='user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ask.Question')),
            ],
        ),
    ]
