# Generated by Django 2.2.24 on 2021-09-05 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ask', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profiles')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('downvoting', models.ManyToManyField(blank=True, related_name='downvoting', to='ask.Question')),
                ('downvotingsq', models.ManyToManyField(blank=True, related_name='downvotingsq', to='ask.SpaceQuestion')),
                ('follower_user', models.ManyToManyField(blank=True, related_name='follower_user', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to='spaces.Spaces')),
                ('following_user', models.ManyToManyField(blank=True, related_name='following_user', to=settings.AUTH_USER_MODEL)),
                ('upvoting', models.ManyToManyField(blank=True, related_name='upvoting', to='ask.Question')),
                ('upvotingsq', models.ManyToManyField(blank=True, related_name='upvotingsq', to='ask.SpaceQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
